name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - 'doc/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'doc/**' 

jobs:
  test:
    name: Test Clojure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: bb test
      - run: bb jar
      - name: Deploy Jars
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: bb deploy
        env:
          CLOJARS_USERNAME: scarlet
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
