name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'doc/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'doc/**'

jobs:
  test:
    name: Test Clojure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: bb test
